import { StyleSheet } from 'react-native';
import type { ThemePalette } from '../../styles/theme/theme';

export const createStyles = (palette: ThemePalette) => StyleSheet.create({
  screen: { flex: 1, backgroundColor: palette.background },
  content: { paddingBottom: 110 },
  header: {
    zIndex: 4, minHeight: 66, paddingHorizontal: 20, paddingVertical: 12,
    flexDirection: `row`, alignItems: `center`, justifyContent: `space-between`,
    borderBottomWidth: 1, borderBottomColor: palette.border, backgroundColor: palette.surface,
  },
  brand: { gap: 10, flexDirection: `row`, alignItems: `center` },
  brandMark: { width: 30, height: 30 },
  brandName: { fontSize: 15, lineHeight: 17, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  brandSub: { fontSize: 9, letterSpacing: 2, color: palette.muted, fontFamily: `Inter` },
  row: { gap: 10, flexDirection: `row`, alignItems: `center` },
  circleButton: { width: 38, height: 38, borderRadius: 19, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.surfaceAlt },
  avatar: { width: 30, height: 32, resizeMode: `contain` },
  hero: { paddingTop: 38, paddingHorizontal: 24, paddingBottom: 28 },
  eyebrow: { fontSize: 10, letterSpacing: 2, color: palette.muted, fontFamily: `Inter`, fontWeight: `700` },
  statusDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: `#71b36b` },
  title: { marginTop: 18, fontSize: 49, lineHeight: 53, letterSpacing: -2.8, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  titleAccent: { color: palette.red },
  body: { marginTop: 15, fontSize: 14, lineHeight: 23, color: palette.muted, fontFamily: `Inter` },
  primaryButton: { minHeight: 47, paddingHorizontal: 18, paddingVertical: 13, borderRadius: 12, flexDirection: `row`, gap: 9, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.red },
  primaryText: { fontSize: 13, color: `#fff`, fontFamily: `Inter`, fontWeight: `700` },
  outlineButton: { minHeight: 45, paddingHorizontal: 16, paddingVertical: 12, borderWidth: 1, borderRadius: 12, borderColor: palette.border, flexDirection: `row`, gap: 7, alignItems: `center`, justifyContent: `center` },
  buttonText: { fontSize: 12, color: palette.text, fontFamily: `Inter`, fontWeight: `600` },
  heroActions: { marginTop: 24, flexDirection: `row`, gap: 10 },
  heroVisual: { marginTop: 30, paddingTop: 13, height: 340, borderRadius: 26, overflow: `hidden`, backgroundColor: palette.surfaceAlt },
  heroCircle: { position: `absolute`, width: 270, height: 270, borderRadius: 135, top: 38, alignSelf: `center`, backgroundColor: palette.green, opacity: 0.5 },
  heroRing: { position: `absolute`, width: 298, height: 298, borderRadius: 149, borderWidth: 1, borderColor: palette.green, top: 24, alignSelf: `center` },
  heroArtwork: { position: `absolute`, width: `100%`, height: 290, top: 5, resizeMode: `contain` },
  heroNumber: { position: `absolute`, right: 16, top: 17, fontSize: 11, color: palette.muted, fontFamily: `Inter` },
  heroFoot: { position: `absolute`, bottom: 18, left: 18, right: 18, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between` },
  heroName: { fontSize: 25, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  heroCategory: { marginTop: 3, fontSize: 11, color: palette.muted, fontFamily: `Inter` },
  heroShiny: { padding: 9, borderWidth: 1, borderRadius: 10, borderColor: palette.border, backgroundColor: palette.surface },
  metricStrip: { marginHorizontal: 24, paddingVertical: 24, flexDirection: `row`, borderTopWidth: 1, borderBottomWidth: 1, borderColor: palette.border },
  metric: { flex: 1, alignItems: `center`, gap: 4 },
  metricValue: { fontSize: 27, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  metricLabel: { fontSize: 10, color: palette.muted, fontFamily: `Inter` },
  section: { paddingTop: 37, paddingHorizontal: 24 },
  sectionHeading: { marginTop: 9, fontSize: 32, lineHeight: 37, letterSpacing: -1.4, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  sectionBody: { marginTop: 9, fontSize: 13, lineHeight: 21, color: palette.muted, fontFamily: `Inter` },
  searchField: { marginTop: 23, minHeight: 49, borderRadius: 13, paddingHorizontal: 15, gap: 10, flexDirection: `row`, alignItems: `center`, backgroundColor: palette.surface, borderWidth: 1, borderColor: palette.border },
  searchInput: { flex: 1, paddingVertical: 12, fontSize: 13, color: palette.text, fontFamily: `Inter` },
  filterRow: { marginTop: 15, gap: 7, paddingBottom: 4 },
  chip: { minHeight: 34, paddingHorizontal: 13, paddingVertical: 9, borderRadius: 9, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.surface },
  chipSelected: { borderColor: palette.green, backgroundColor: palette.green },
  chipText: { fontSize: 11, color: palette.muted, fontFamily: `Inter`, textTransform: `capitalize` },
  chipTextSelected: { color: `#17251b`, fontWeight: `700` },
  resultCount: { marginTop: 14, marginBottom: 13, fontSize: 10, color: palette.muted, fontFamily: `Inter` },
  grid: { gap: 16 },
  skeleton: { padding: 20, height: 370, borderWidth: 1, borderRadius: 20, borderColor: palette.border, backgroundColor: palette.surface },
  skeletonLine: { height: 12, borderRadius: 5, backgroundColor: palette.surfaceAlt, marginBottom: 10 },
  skeletonImage: { height: 190, borderRadius: 16, backgroundColor: palette.surfaceAlt, marginVertical: 10 },
  feedback: { borderWidth: 1, borderRadius: 16, padding: 20, borderColor: palette.border, backgroundColor: palette.surface },
  feedbackTitle: { fontSize: 18, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  feedbackBody: { marginTop: 8, marginBottom: 16, fontSize: 13, lineHeight: 21, color: palette.muted, fontFamily: `Inter` },
  more: { marginTop: 20 },
  regionCard: { marginTop: 16, minHeight: 112, padding: 17, borderWidth: 1, borderRadius: 16, flexDirection: `row`, alignItems: `center`, justifyContent: `space-between`, borderColor: palette.border, backgroundColor: palette.surface },
  regionTitle: { marginTop: 5, fontSize: 23, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  regionMeta: { marginTop: 5, fontSize: 11, color: palette.muted, fontFamily: `Inter` },
  regionArt: { width: 86, height: 86, resizeMode: `contain` },
  featureCard: { marginTop: 17, padding: 22, borderRadius: 20, backgroundColor: palette.surfaceAlt },
  featureTitle: { marginTop: 13, fontSize: 23, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  featureCopy: { marginTop: 9, marginBottom: 19, fontSize: 13, lineHeight: 22, color: palette.muted, fontFamily: `Inter` },
  code: { padding: 17, marginBottom: 18, borderRadius: 11, color: `#a8db9f`, backgroundColor: `#18251e`, fontFamily: `SpaceGrotesk`, fontSize: 11, lineHeight: 20 },
  footer: { paddingHorizontal: 24, paddingTop: 45, gap: 17 },
  footerLinks: { flexDirection: `row`, flexWrap: `wrap`, gap: 20 },
  footerLink: { fontSize: 12, color: palette.muted, fontFamily: `Inter` },
  footerCopy: { fontSize: 10, lineHeight: 17, color: palette.muted, fontFamily: `Inter` },
  tabBar: { position: `absolute`, bottom: 0, left: 0, right: 0, paddingTop: 10, paddingHorizontal: 19, borderTopWidth: 1, borderColor: palette.border, backgroundColor: palette.surface, flexDirection: `row`, justifyContent: `space-around` },
  tab: { minWidth: 62, padding: 7, gap: 4, alignItems: `center` },
  tabText: { fontSize: 10, color: palette.muted, fontFamily: `Inter` },
  tabActive: { color: palette.red, fontWeight: `700` },
  scrollTop: { position: `absolute`, right: 18, bottom: 92, width: 42, height: 42, borderRadius: 21, alignItems: `center`, justifyContent: `center`, backgroundColor: palette.red, elevation: 5 },
  modalScrim: { flex: 1, justifyContent: `flex-end`, backgroundColor: `rgba(5, 14, 9, .6)` },
  detailSheet: { maxHeight: `91%`, borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 24, backgroundColor: palette.surface },
  detailHeader: { flexDirection: `row`, alignItems: `center`, justifyContent: `space-between`, marginBottom: 16 },
  detailTitle: { fontSize: 28, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  detailArtwork: { height: 215, width: `100%`, resizeMode: `contain` },
  detailSubtitle: { marginTop: 21, marginBottom: 11, fontSize: 19, color: palette.text, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  detailDescription: { color: palette.muted, fontSize: 13, lineHeight: 22, fontFamily: `Inter` },
  evolution: { gap: 5, marginBottom: 14, padding: 14, borderRadius: 12, backgroundColor: palette.surfaceAlt },
  evolutionName: { fontSize: 13, color: palette.text, fontFamily: `Inter`, fontWeight: `700` },
  evolutionMethod: { fontSize: 12, color: palette.muted, fontFamily: `Inter`, lineHeight: 19 },
  statRow: { flexDirection: `row`, gap: 12, alignItems: `center`, marginBottom: 9 },
  statLabel: { width: 100, fontSize: 11, color: palette.muted, fontFamily: `Inter`, textTransform: `capitalize` },
  statTrack: { flex: 1, height: 6, borderRadius: 3, overflow: `hidden`, backgroundColor: palette.surfaceAlt },
  statFill: { height: 6, borderRadius: 3, backgroundColor: palette.green },
  statValue: { width: 29, textAlign: `right`, fontSize: 11, color: palette.text, fontFamily: `Inter` },
  loader: { position: `absolute`, top: 0, bottom: 0, left: 0, right: 0, zIndex: 30 },
  loaderTop: { position: `absolute`, top: 0, left: 0, right: 0, height: `50%`, borderBottomWidth: 7, borderColor: `#162119`, backgroundColor: palette.red, justifyContent: `flex-end`, alignItems: `center`, paddingBottom: 74 },
  loaderBottom: { position: `absolute`, bottom: 0, left: 0, right: 0, height: `50%`, borderTopWidth: 7, borderColor: `#162119`, backgroundColor: palette.background, justifyContent: `flex-start`, alignItems: `center`, paddingTop: 78 },
  loaderBrand: { fontSize: 13, letterSpacing: 4, color: `#fff`, fontFamily: `SpaceGrotesk`, fontWeight: `700` },
  loaderText: { fontSize: 10, letterSpacing: 2, color: palette.muted, fontFamily: `Inter` },
  loaderButtonWrap: { position: `absolute`, top: `50%`, left: `50%`, marginTop: -42, marginLeft: -42, width: 84, height: 84, borderRadius: 42, padding: 10, backgroundColor: `#162119` },
  loaderButton: { flex: 1, borderWidth: 4, borderColor: `#d2dbce`, borderRadius: 32, justifyContent: `center`, alignItems: `center`, backgroundColor: `#fff` },
  loaderLens: { width: 19, height: 19, borderRadius: 10, backgroundColor: palette.green },
});
