import { StyleSheet } from 'react-native';
import { ThemePalette } from '../../styles/theme/theme';

export const createTrainerStyles = (palette: ThemePalette) => StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: `rgba(9,21,15,.58)`, justifyContent: `flex-end` },
  keyboard: { maxHeight: `95%` },
  safe: { backgroundColor: palette.surface, borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: `hidden` },
  scroll: { padding: 24, paddingBottom: 28 },
  header: { flexDirection: `row`, justifyContent: `space-between`, alignItems: `center`, marginBottom: 20 },
  eyebrow: { fontSize: 10, fontWeight: `800`, color: palette.muted, letterSpacing: 1.6 },
  close: { width: 36, height: 36, borderRadius: 18, backgroundColor: palette.surfaceAlt, alignItems: `center`, justifyContent: `center` },
  closeText: { color: palette.text, fontSize: 26, marginTop: -2 },
  title: { color: palette.text, fontSize: 28, fontWeight: `800`, letterSpacing: -1.1, marginBottom: 10 },
  intro: { color: palette.muted, fontSize: 13, lineHeight: 21, marginBottom: 22 },
  tabs: { flexDirection: `row`, padding: 5, gap: 5, borderRadius: 12, backgroundColor: palette.surfaceAlt, marginBottom: 20 },
  tab: { flex: 1, padding: 11, borderRadius: 9, alignItems: `center` },
  activeTab: { backgroundColor: palette.surface },
  tabLabel: { color: palette.text, fontSize: 12, fontWeight: `700` },
  label: { color: palette.text, fontSize: 12, fontWeight: `700`, marginBottom: 7 },
  input: { color: palette.text, fontSize: 14, padding: 14, borderRadius: 11, borderWidth: 1, borderColor: palette.border, backgroundColor: palette.background, marginBottom: 16 },
  readonly: { color: palette.muted },
  primary: { backgroundColor: palette.text, padding: 15, borderRadius: 11, alignItems: `center`, marginTop: 4 },
  primaryText: { color: palette.surface, fontSize: 13, fontWeight: `700` },
  disabled: { opacity: .5 },
  switch: { alignItems: `center`, marginTop: 16, gap: 8 },
  muted: { color: palette.muted, fontSize: 12, lineHeight: 19 },
  textButton: { color: palette.text, fontSize: 12, fontWeight: `700` },
  feedback: { padding: 13, marginBottom: 18, backgroundColor: palette.surfaceAlt, borderRadius: 11 },
  feedbackText: { color: palette.text, fontSize: 12, lineHeight: 19 },
  error: { color: palette.red },
  rosterHeading: { flexDirection: `row`, justifyContent: `space-between`, marginBottom: 12 },
  roster: { flexDirection: `row`, flexWrap: `wrap`, gap: 8, marginBottom: 8 },
  trainer: { width: `23%`, minWidth: 60, alignItems: `center`, paddingVertical: 10, backgroundColor: palette.background, borderWidth: 1, borderColor: palette.border, borderRadius: 11 },
  selectedTrainer: { borderColor: palette.green, backgroundColor: palette.surfaceAlt },
  trainerImage: { width: 55, height: 74 },
  trainerName: { color: palette.text, fontSize: 11, fontWeight: `700`, marginTop: 6 },
  trainerGen: { color: palette.muted, fontSize: 8, letterSpacing: .8, marginTop: 3 },
  selectedMark: { color: palette.text, fontSize: 10, position: `absolute`, top: 4, right: 5 },
  rosterNote: { color: palette.muted, fontSize: 10, lineHeight: 17, marginBottom: 16 },
  footer: { borderTopWidth: 1, borderColor: palette.border, paddingTop: 18, marginTop: 24, gap: 14 },
  footerText: { color: palette.muted, fontSize: 10, lineHeight: 17 },
  capacityRow: { flexDirection: `row`, gap: 8, marginBottom: 14 },
  capacity: { flex: 1, alignItems: `center`, padding: 11, borderWidth: 1, borderColor: palette.border, borderRadius: 10, backgroundColor: palette.background },
  selectedCapacity: { borderColor: palette.green, backgroundColor: palette.surfaceAlt },
  pending: { padding: 12, backgroundColor: palette.surfaceAlt, borderRadius: 13, flexDirection: `row`, alignItems: `center`, gap: 15, marginBottom: 20 },
  pokemonImage: { width: 62, height: 62 },
  pendingName: { color: palette.text, fontSize: 17, fontWeight: `700`, textTransform: `capitalize`, marginTop: 3 },
  team: { borderWidth: 1, borderColor: palette.border, padding: 15, borderRadius: 13, marginTop: 15 },
  teamHeader: { flexDirection: `row`, justifyContent: `space-between`, alignItems: `center`, marginBottom: 14 },
  teamName: { color: palette.text, fontSize: 15, fontWeight: `700`, marginBottom: 4 },
  slots: { flexDirection: `row`, flexWrap: `wrap`, gap: 6 },
  slot: { width: `23%`, minWidth: 54, minHeight: 78, alignItems: `center`, justifyContent: `center`, borderWidth: 1, borderColor: palette.border, borderRadius: 9, backgroundColor: palette.background },
  slotImage: { width: 46, height: 46 },
  slotName: { color: palette.text, fontSize: 8, textTransform: `capitalize`, maxWidth: `100%` },
  remove: { position: `absolute`, top: 2, right: 4, width: 18, height: 18, alignItems: `center`, justifyContent: `center` },
  removeText: { color: palette.muted, fontSize: 14 },
  slotPlus: { color: palette.border, fontSize: 25 },
  skeletonLine: { height: 46, borderRadius: 11, backgroundColor: palette.surfaceAlt, marginTop: 16 },
  empty: { alignItems: `center`, gap: 12, padding: 22, marginTop: 16, borderRadius: 13, borderWidth: 1, borderStyle: `dashed`, borderColor: palette.border },
  emptyTitle: { color: palette.text, fontSize: 15, fontWeight: `700`, textAlign: `center` },
});
